services:
  agaro-postgres:
    image: postgres:17
    container_name: agaro-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - agaro_postgres_data:/var/lib/postgresql/data
      - ./postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./certs/:/etc/letsencrypt/live/ardial.tech/
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf

    command: >
      postgres
      -c config_file=/etc/postgresql/postgresql.conf
      -c hba_file=/etc/postgresql/pg_hba.conf
      -c listen_addresses='*'

    networks:
      - agaro-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  agaro-adminer:
    image: adminer:latest
    container_name: agaro-adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: agaro-postgres
    ports:
      - "8080:8080"
    depends_on:
      - agaro-postgres
    networks:
      - agaro-network

  agaro-anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: agaro-anvil
    entrypoint: ["anvil"]
    command: >
      --host 0.0.0.0
      --chain-id 13377
      --block-time 5
      --gas-limit 30000000
      --base-fee 1000000000
    ports:
      - "8545:8545"
    networks:
      - agaro-network

  agaro-redis:
    image: redis:latest
    container_name: agaro-redis
    restart: unless-stopped
    env_file:
      - .env
    command:
      [
        "redis-server",
        "--requirepass",
        "${REDIS_PASSWORD}",
        "--tls-port",
        "8882",
        "--port",
        "0",
        "--tls-cert-file",
        "/etc/redis/ssl/fullchain.pem",
        "--tls-key-file",
        "/etc/redis/ssl/privkey.pem",
        "--tls-ca-cert-file",
        "/etc/redis/ssl/chain.pem",
        "--tls-auth-clients",
        "no",
      ]
    ports:
      - "8882:8882"
    volumes:
      - agaro_redis_data:/data
      - ./certs/:/etc/redis/ssl/
    extra_hosts:
      - "ardial.tech:127.0.0.1"
    networks:
      - agaro-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  agaro-redisinsight:
    image: redislabs/redisinsight:latest
    container_name: agaro-redisinsight
    restart: unless-stopped
    ports:
      - "8883:5540"
    volumes:
      - agaro_redisinsight_data:/db
    depends_on:
      - agaro-redis

networks:
  agaro-network:
    name: agaro-network
    external: true

volumes:
  agaro_postgres_data:
    name: agaro_postgres_data
  agaro_redis_data:
    name: agaro_redis_data
  agaro_redisinsight_data:
    name: agaro_redisinsight_data
