services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    entrypoint: ["anvil"]
    command: >
      --host 0.0.0.0
      --chain-id 1337
      --block-time 5
      --gas-limit 30000000
      --base-fee 1000000000
    ports:
      - "8545:8545"
    networks:
      - ethnet

networks:
  ethnet:
    driver: bridge
