name: Backend Docker Build & Deploy

on:
  push:
    branches: ["main", "dev-agaro"]
    paths:
      - "AGARO-MAIN-BE/**"
  workflow_dispatch:

env:
  DOCKER_IMAGE: ardialqlause/agaro-main-be
  CONTAINER_NAME: agaro-be
  PORT: 3005
  ENV_FILE: .env
  REMOTE_DIR: /home/ardial/agaro-be

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set tag, port, env secret, container name, and remote dir based on branch
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
            echo "PORT=3005" >> $GITHUB_ENV
            echo "ENV_SECRET=${{ secrets.ENV_PROD }}" >> $GITHUB_ENV
            echo "CONTAINER_NAME=${{ env.CONTAINER_NAME }}" >> $GITHUB_ENV
            echo "REMOTE_DIR=/home/ardial/agaro-be" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "dev-agaro" ]]; then
            echo "TAG=dev" >> $GITHUB_ENV
            echo "PORT=3505" >> $GITHUB_ENV
            echo "ENV_SECRET=${{ secrets.ENV_PROD_DEV }}" >> $GITHUB_ENV
            echo "CONTAINER_NAME=${{ env.CONTAINER_NAME }}-dev" >> $GITHUB_ENV
            echo "REMOTE_DIR=/home/ardial/agaro-be-dev" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./AGARO-MAIN-BE
          file: ./AGARO-MAIN-BE/Dockerfile.prod
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Create env file from secret
        run: |
          echo "${{ env.ENV_SECRET }}" > ./AGARO-MAIN-BE/${{ env.ENV_FILE }}
          echo "Environment file created"
          cat ./AGARO-MAIN-BE/${{ env.ENV_FILE }}

      - name: Upload env file to server
        run: |
          echo "Creating directory on remote server if not exists..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "mkdir -p ${{ env.REMOTE_DIR }}"
          echo "Uploading environment file..."
          scp -o StrictHostKeyChecking=no ./AGARO-MAIN-BE/${{ env.ENV_FILE }} \
            ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ env.REMOTE_DIR }}/${{ env.ENV_FILE }}

      - name: Deploy to Server
        run: |
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "
            sudo bash -c '
              echo \"Pulling latest Docker image\"
              docker pull ${{ env.DOCKER_IMAGE }}:${{ env.TAG }}

              echo \"Stopping old container\"
              docker stop ${{ env.CONTAINER_NAME }} 2>/dev/null || true
              docker rm ${{ env.CONTAINER_NAME }} 2>/dev/null || true

              echo \"Cleaning unused containers/images\"
              docker container prune -f
              docker image prune -f

              echo \"Running new container on port ${{ env.PORT }}\"
              docker run -d \
                --name ${{ env.CONTAINER_NAME }} \
                --restart unless-stopped \
                --network agaro-network \
                -p 127.0.0.1:${{ env.PORT }}:${{ env.PORT }} \
                --env-file ${{ env.REMOTE_DIR }}/${{ env.ENV_FILE }} \
                ${{ env.DOCKER_IMAGE }}:${{ env.TAG }}
            '
          "
