name: Backend Docker Build & Deploy

on:
  push:
    branches: ["main"]
    paths:
      - "AGARO-MAIN-BE/**"
  workflow_dispatch:

env:
  DOCKER_IMAGE: ardialqlause/agaro-main-be
  CONTAINER_NAME: agaro-main-be
  PORT: 4000

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./AGARO-MAIN-BE              # 👈 build context = backend folder
          file: ./AGARO-MAIN-BE/Dockerfile.prod # 👈 Dockerfile location
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 92.113.145.8 >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh ardial@92.113.145.8 '
            sudo bash -c "
              echo '--- Pulling latest Docker image ---'
              docker pull ${{ env.DOCKER_IMAGE }}:latest
              
              echo '--- Stopping old container ---'
              docker stop ${{ env.CONTAINER_NAME }} 2>/dev/null || true
              docker rm ${{ env.CONTAINER_NAME }} 2>/dev/null || true
              
              echo '--- Clearing port ${{ env.PORT }} ---'
              port_containers=\$(docker ps -q --filter \"publish=${{ env.PORT }}\")
              if [ -n \"\$port_containers\" ]; then
                docker stop \$port_containers
                docker rm \$port_containers
              fi
              
              lsof -ti:${{ env.PORT }} | xargs kill -9 2>/dev/null || true
              
              echo '--- Cleaning unused containers/images ---'
              docker container prune -f
              docker image prune -f
              
              echo '--- Running new container ---'
              docker run -d \
                --name ${{ env.CONTAINER_NAME }} \
                --restart unless-stopped \
                -p 127.0.0.1:${{ env.PORT }}:${{ env.PORT }} \
                ${{ env.DOCKER_IMAGE }}:latest
            "
          '

