name: AGARO-CONTRACT Hardhat Tests

on:
  push:
    branches: ["main"]
    paths:
      - "AGARO-CONTRACT/**"
  pull_request:
    branches: ["main"]
    paths:
      - "AGARO-CONTRACT/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./AGARO-CONTRACT

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use latest Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "npm"
          cache-dependency-path: ./AGARO-CONTRACT/package-lock.json

      - name: Install dependencies
        run: npm i

      - name: Compile contracts
        run: npm run build

      - name: Run Hardhat tests
        run: npm test
