name: Event Listener

on:
  push:
    branches: ["main"]
    paths:
      - "AGARO-EVENT-LISTENER/**"
  workflow_dispatch:

env:
  APP_NAME: agaro-event-listener
  DEPLOY_DIR: /opt/agaro-event-listener
  PORT: 3002

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release binary
        run: |
          cd AGARO-EVENT-LISTENER
          cargo build --release
          mkdir -p dist
          cp target/release/agaro-event-listener dist/
          cp -r abi dist/
          cd dist
          tar -czf agaro-event-listener.tar.gz agaro-event-listener abi

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Upload and deploy to server
        run: |
          echo "Uploading package to server..."
          scp AGARO-EVENT-LISTENER/dist/agaro-event-listener.tar.gz \
            ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/tmp/

          echo "Deploying and restarting service..."
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "
            set -e

            echo 'Extracting new version...'
            sudo mkdir -p ${{ env.DEPLOY_DIR }}
            sudo tar -xzf /tmp/agaro-event-listener.tar.gz -C ${{ env.DEPLOY_DIR }}
            sudo rm /tmp/agaro-event-listener.tar.gz

            echo 'Stopping existing service (if running)...'
            sudo systemctl stop agaro-event-listener.service || true

            echo 'Starting new service...'
            sudo systemctl start agaro-event-listener.service

            echo 'Verifying service status...'
            sleep 2
            if ! sudo systemctl is-active --quiet agaro-event-listener.service; then
              echo 'Service failed to start!'
              sudo systemctl status agaro-event-listener.service --no-pager
              exit 1
            else
              echo 'Service is active and running.'
            fi
          "
